### ISSUE TITLE
Initial chat with PHIN VADS System Owner and Developer

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/phinvads-go#2]
Will be chatting with Dishant Patel, Roniqua Watkins, and George Chen about PHIN VADS.

**Comment by KeepAustinWired** [comment]
Share recording + Notes

**Comment by nickclyde** [comment]
Recording + notes here: https://pear-toucan-cw3h.dovetail.com/data/7rRv8Tq1AgrCALr26meQuA
