### ISSUE TITLE
Rapid prototype PHIN VADS Cached API

### ISSUE THREAD

**Issue by akasper** [CDCgov/phinvads-go#3]
In order to validate assumptions about the core purpose of Vocabulizer
As a Skylight engineer, 
I want to provide a rough prototype of what I consider to be the target deliverable: a caching layer for PHIN VADS
In order to better analyze public health data
As a public health data engineer
I want a service that allows me to find code systems and value sets with minimal delay

Later on, we may expand this API to cache response from other vocabulary services as well, effectively creating a datamart.

**Comment by akasper** [comment]
@nickclyde and I had discussed the value of _just delivering something_ in order to get stakeholder feedback. We consider this to be the lowest-hanging fruit: throwaway code that demonstrates how data vocabulary API results might be intermingled

**Comment by nickclyde** [comment]
In order to make development as fast as possible, we can use [fastapi](https://fastapi.tiangolo.com/) and https://github.com/long2ice/fastapi-cache

**Comment by nickclyde** [comment]
In order to make development as fast as possible, we can use [fastapi](https://fastapi.tiangolo.com/) and https://github.com/long2ice/fastapi-cache

**Comment by akasper** [comment]
After some discussion with @nickclyde, we have decided that the simplest incremental step is simply to write an API wrapper for PHIN VADS.

**Comment by nickclyde** [comment]
Initial prototype complete.
